services:
  backend:
    image: ghcr.io/${GHCR_IMAGE_OWNER}/${GHCR_IMAGE_REPO}-backend:latest
    container_name: ondent-backend
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_MONGO: ${DATABASE_MONGO}
      PORT: ${PORT:-4000}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      DEFAULT_USER_PASSWORD: ${DEFAULT_USER_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
    ports:
      - "${API_PORT:-4000}:4000"
    networks:
      - app-network

  frontend:
    image: ghcr.io/${GHCR_IMAGE_OWNER}/${GHCR_IMAGE_REPO}-frontend:latest
    container_name: ondent-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    external: true
